# image will be published to ghcr.io/<user>/<name>
name: bazzite-gnome
# description will be included in the image's metadata
description: This is my personal OS image based on ublue-os/bazzite-gnome (AMD/Intel).

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
modules:
  - from-file: modules/packages.yml
  - from-file: modules/files.yml
  - from-file: modules/scripts.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
