name: 'Build frequency: git'

on:
  schedule:
    - cron: "00 07 * * 0" # 07:00 UTC every Sunday
  push:
    paths-ignore:
      - '/toolboxes/**'
      - "**.md"
    branches-ignore:
      - 'dependabot**'
      - 'compiler'
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - images/kova-hypr/current/kova-hypr--current-git.yml
          - images/kova-hypr/previous/kova-hypr--previous-git.yml

          - images/kova/current/kova--current-git.yml
          - images/kova/previous/kova--previous-git.yml

          - images/silvara-hypr/current/silvara-hypr--current-git.yml
          - images/silvara-hypr/previous/silvara-hypr--previous-git.yml
          
          - images/silvara/current/silvara--current-git.yml
          - images/silvara/previous/silvara--previous-git.yml

    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.7
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
