name: Stable Stream (weekly, git)
on:
  schedule:
    - cron: "00 07 * * 2" # 07:00 UTC every Tuesday
  push:
    paths-ignore:
      - '/toolboxes/**'
      - "**.md"
    branches-ignore:
      - 'dependabot**'
      - 'compiler'

  pull_request:
  workflow_dispatch:
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - images/aurora/dx/stable/aurora-dx--stable-git.yml
          - images/aurora/regular/stable/aurora--stable-git.yml
          - images/bluefin/dx/stable/bluefin-dx--stable-git.yml
          - images/bluefin/regular/stable/bluefin--stable-git.yml
          - images/aurora-hypr/dx/stable/aurora-hypr-dx--stable-git.yml
          - images/aurora-hypr/regular/stable/aurora-hypr--stable-git.yml
          - images/bluefin-hypr/dx/stable/bluefin-hypr-dx--stable-git.yml
          - images/bluefin-hypr/regular/stable/bluefin-hypr--stable-git.yml

    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.7
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
